/*
Lib for ESP32C3 INTERRUPT Register Address
See page 196 Technical Reference for details
*/

/*
CPU Peripheral Interrupt Registers and Peripheral Interrupt Sources
See table 8.1 page 196 Technical Reference for details
*/

#ifndef _INTERRUPT_CORE0_REG_H_
#define _INTERRUPT_CORE0_REG_H_
#include "regBase.h"

// Interrupt Source Mapping Registers
// All R/W
#define INTERRUPT_CORE0_PWR_INTR_MAP_REG (C3_INTERRUPT + 0x0008)
#define INTERRUPT_CORE0_I2C_MST_INT_MAP_REG (C3_INTERRUPT + 0x002C)
#define INTERRUPT_CORE0_SLC0_INTR_MAP_REG (C3_INTERRUPT + 0x0030)
#define INTERRUPT_CORE0_SLC1_INTR_MAP_REG (C3_INTERRUPT + 0x0034)
#define INTERRUPT_CORE0_APB_CTRL_INTR_MAP_REG (C3_INTERRUPT + 0x0038)
#define INTERRUPT_CORE0_UHCI0_INTR_MAP_REG (C3_INTERRUPT + 0x003C)
#define INTERRUPT_CORE0_GPIO_INTERRUPT_PRO_MAP_REG (C3_INTERRUPT + 0x0040)
#define INTERRUPT_CORE0_GPIO_INTERRUPT_PRO_NMI_MAP_REG (C3_INTERRUPT + 0x0044)
#define INTERRUPT_CORE0_SPI_INTR_1_MAP_REG (C3_INTERRUPT + 0x0048)
#define INTERRUPT_CORE0_SPI_INTR_2_MAP_REG (C3_INTERRUPT + 0x004C)
#define INTERRUPT_CORE0_I2S1_INT_MAP_REG (C3_INTERRUPT + 0x0050)
#define INTERRUPT_CORE0_UART_INTR_MAP_REG (C3_INTERRUPT + 0x0054)
#define INTERRUPT_CORE0_UART1_INTR_MAP_REG (C3_INTERRUPT + 0x0058)
#define INTERRUPT_CORE0_LEDC_INT_MAP_REG (C3_INTERRUPT + 0x005C)
#define INTERRUPT_CORE0_EFUSE_INT_MAP_REG (C3_INTERRUPT + 0x0060)
#define INTERRUPT_CORE0_TWAI_INT_MAP_REG (C3_INTERRUPT + 0x0064)
#define INTERRUPT_CORE0_USB_INTR_MAP_REG (C3_INTERRUPT + 0x0068)
#define INTERRUPT_CORE0_RTC_CORE_INTR_MAP_REG (C3_INTERRUPT + 0x006C)
#define INTERRUPT_CORE0_RMT_INTR_MAP_REG (C3_INTERRUPT + 0x0070)
#define INTERRUPT_CORE0_I2C_EXT0_INTR_MAP_REG (C3_INTERRUPT + 0x0074)
#define INTERRUPT_CORE0_TIMER_INT1_MAP_REG (C3_INTERRUPT + 0x0078)
#define INTERRUPT_CORE0_TIMER_INT2_MAP_REG (C3_INTERRUPT + 0x007C)
#define INTERRUPT_CORE0_TG_T0_INT_MAP_REG (C3_INTERRUPT + 0x0080)
#define INTERRUPT_CORE0_TG_WDT_INT_MAP_REG (C3_INTERRUPT + 0x0084)
#define INTERRUPT_CORE0_TG1_T0_INT_MAP_REG (C3_INTERRUPT + 0x0088)
#define INTERRUPT_CORE0_TG1_WDT_INT_MAP_REG (C3_INTERRUPT + 0x008C)
#define INTERRUPT_CORE0_CACHE_IA_INT_MAP_REG (C3_INTERRUPT + 0x0090)
#define INTERRUPT_CORE0_SYSTIMER_TARGET0_INT_MAP_REG (C3_INTERRUPT + 0x0094)
#define INTERRUPT_CORE0_SYSTIMER_TARGET1_INT_MAP_REG (C3_INTERRUPT + 0x0098)
#define INTERRUPT_CORE0_SYSTIMER_TARGET2_INT_MAP_REG (C3_INTERRUPT + 0x009C)
#define INTERRUPT_CORE0_SPI_MEM_REJECT_INTR_MAP_REG (C3_INTERRUPT + 0x00A0)
#define INTERRUPT_CORE0_ICACHE_PRELOAD_INT_MAP_REG (C3_INTERRUPT + 0x00A4)
#define INTERRUPT_CORE0_ICACHE_SYNC_INT_MAP_REG (C3_INTERRUPT + 0x00A8)
#define INTERRUPT_CORE0_APB_ADC_INT_MAP_REG (C3_INTERRUPT + 0x00AC)
#define INTERRUPT_CORE0_DMA_CH0_INT_MAP_REG (C3_INTERRUPT + 0x00B0)
#define INTERRUPT_CORE0_DMA_CH1_INT_MAP_REG (C3_INTERRUPT + 0x00B4)
#define INTERRUPT_CORE0_DMA_CH2_INT_MAP_REG (C3_INTERRUPT + 0x00B8)
#define INTERRUPT_CORE0_RSA_INT_MAP_REG (C3_INTERRUPT + 0x00BC)
#define INTERRUPT_CORE0_AES_INT_MAP_REG (C3_INTERRUPT + 0x00C0)
#define INTERRUPT_CORE0_SHA_INT_MAP_REG (C3_INTERRUPT + 0x00C4)
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_0_MAP_REG (C3_INTERRUPT + 0x00C8)
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_1_MAP_REG (C3_INTERRUPT + 0x00CC)
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_2_MAP_REG (C3_INTERRUPT + 0x00D0)
#define INTERRUPT_CORE0_CPU_INTR_FROM_CPU_3_MAP_REG (C3_INTERRUPT + 0x00D4)
#define INTERRUPT_CORE0_ASSIST_DEBUG_INTR_MAP_REG (C3_INTERRUPT + 0x00D8)
#define INTERRUPT_CORE0_DMA_APBPERI_PMS_MONITOR_VIOLATE_INTR_MAP_REG (C3_INTERRUPT + 0x00DC)
#define INTERRUPT_CORE0_CORE_0_IRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_REG (C3_INTERRUPT + 0x00E0)
#define INTERRUPT_CORE0_CORE_0_DRAM0_PMS_MONITOR_VIOLATE_INTR_MAP_REG (C3_INTERRUPT + 0x00E4)
#define INTERRUPT_CORE0_CORE_0_PIF_PMS_MONITOR_VIOLATE_INTR_MAP_REG (C3_INTERRUPT + 0x00E8)
#define INTERRUPT_CORE0_CORE_0_PIF_PMS_MONITOR_VIOLATE_SIZE_INTR_MAP_REG (C3_INTERRUPT + 0x00EC)
#define INTERRUPT_CORE0_BACKUP_PMS_VIOLATE_INTR_MAP_REG (C3_INTERRUPT + 0x00F0)
#define INTERRUPT_CORE0_CACHE_CORE0_ACS_INT_MAP_REG (C3_INTERRUPT + 0x00F4)
// Source map bit field (write to thisfile isr_number)
#define SOURCE_MAP_LSB   0
#define SOURCE_MAP_MSB   4

// Interrupt Source Status Registers
#define INTERRUPT_CORE0_INTR_STATUS_0_REG (C3_INTERRUPT + 0x00F8)   //RO
#define INTERRUPT_CORE0_INTR_STATUS_1_REG (C3_INTERRUPT + 0x00FC)   //RO

// Clock Register
#define INTERRUPT_CORE0_CLOCK_GATE_REG (C3_INTERRUPT + 0x0100)  //R/W

// CPU Interrupt Registers
#define INTERRUPT_CORE0_CPU_INT_ENABLE_REG (C3_INTERRUPT + 0x0104)  //R/W
#define INTERRUPT_CORE0_CPU_INT_TYPE_REG (C3_INTERRUPT + 0x0108)    //R/W
#define INTERRUPT_CORE0_CPU_INT_CLEAR_REG (C3_INTERRUPT + 0x010C)   //R/W
#define INTERRUPT_CORE0_CPU_INT_EIP_STATUS_REG (C3_INTERRUPT + 0x0110)  //RO
// Set priority for CPU interrupt nth
#define INTERRUPT_CORE0_CPU_INT_PRI_REG_BASE (C3_INTERRUPT + 0x0118)
#define INTERRUPT_CORE0_CPU_INT_PRI_REG(isr_number) (INTERRUPT_CORE0_CPU_INT_PRI_REG_BASE + 4*isr_number) //RW
// Bit field for interrupt priority (15 = highest)
#define PRI_MAP_LSB     0
#define PRI_MAP_MSB     3
#define INTERRUPT_CORE0_CPU_INT_THRESH_REG (C3_INTERRUPT + 0x0194)  //R/W
// Bit field for interrupt threshold
#define INT_THRESH_LSB     0
#define INT_THRESH_MSB     3
// Version Register
#define INTERRUPT_CORE0_INTERRUPT_DATE_REG (C3_INTERRUPT + 0x07FC)  //R/W


// List of source number to CPU Interrupt configuration
#define UHCI0_INTR 15
#define GPIO_PROCPU_INTR 16
#define GPIO_PROCPU_NMI_INTR 17
#define GPSPI2_INTR_2 19
#define I2S_INTR 20
#define UART_INTR 21
#define UART1_INTR 22
#define LEDC_INTR 23
#define EFUSE_INTR 24
#define TWAI_INTR 25
#define USB_SERIAL_JTAG_INTR 26
#define RTC_CNTL_INTR 27
#define RMT_INTR 28
#define I2C_EXT0_INTR 29
#define TG_T0_INTR 32
#define TG_WDT_INTR 33
#define TG1_T0_INTR 34
#define TG1_WDT_INTR 35
#define SYSTIMER_TARGET0_INTR 37
#define SYSTIMER_TARGET1_INTR 38
#define SYSTIMER_TARGET2_INTR 39
#define vDIGTAL_ADC_INTR 43
#define GDMA_CH0_INTR 44
#define GDMA_CH1_INTR 45
#define GDMA_CH2_INTR 46
#define RSA_INTR 47
#define AES_INTR 48
#define SHA_INTR 49
#define SW_INTR_0 50
#define SW_INTR_1 51
#define SW_INTR_2 52
#define SW_INTR_3 53
#define ASSIST_DEBUG_INTR 54
#define PMS_DMA_VIO_INTR 55
#define PMS_IBUS_VIO_INTR 56
#define PMS_DBUS_VIO_INTR 57
#define PMS_PERI_VIO_INTR 58
#define MS_PERI_VIO_SIZE_INTR 59

#endif